apiVersion: 1
datasources:
  - name: Nexspence-Prometheus
    type: prometheus
    uid: nexspence-prom
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    jsonData:
      timeInterval: 15s
