apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nexspence.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nexspence.labels" . | nindent 4 }}
type: Opaque
stringData:
  NEXSPENCE_DATABASE_DSN: {{ include "nexspence.databaseDSN" . | quote }}
  NEXSPENCE_AUTH_JWT_SECRET: {{ .Values.config.jwtSecret | quote }}
  NEXSPENCE_BOOTSTRAP_ADMIN_PASSWORD: {{ .Values.config.adminPassword | quote }}
  {{- if eq .Values.storage.type "s3" }}
  NEXSPENCE_STORAGE_S3_ACCESS_KEY: {{ .Values.storage.s3.accessKey | quote }}
  NEXSPENCE_STORAGE_S3_SECRET_KEY: {{ .Values.storage.s3.secretKey | quote }}
  {{- end }}
