-- +goose Up
-- Allow multiple users without an email address (e.g. LDAP users that have no
-- mail attribute). Previously email was NOT NULL UNIQUE, which caused a
-- duplicate key error when two LDAP users with no email tried to log in.
--
-- Strategy:
--   1. Drop the NOT NULL constraint so we can store NULL for missing emails.
--   2. Convert any existing empty-string emails to NULL.
--   3. Replace the blanket UNIQUE constraint with a partial index that only
--      enforces uniqueness for non-NULL, non-empty email addresses.

ALTER TABLE users ALTER COLUMN email DROP NOT NULL;

UPDATE users SET email = NULL WHERE email = '';

-- Drop the old constraint (created by the NOT NULL UNIQUE column definition).
-- The constraint name is generated by PostgreSQL as <table>_<column>_key.
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_email_key;

-- Partial unique index: two users with email=NULL or email='' are allowed;
-- two users with the same real email are not.
CREATE UNIQUE INDEX IF NOT EXISTS users_email_nonempty_key
    ON users(email)
    WHERE email IS NOT NULL AND email <> '';

-- +goose Down
DROP INDEX IF EXISTS users_email_nonempty_key;

UPDATE users SET email = '' WHERE email IS NULL;

ALTER TABLE users ALTER COLUMN email SET NOT NULL;

ALTER TABLE users
    ADD CONSTRAINT users_email_key UNIQUE (email);
