package auth

import (
	"context"
	"errors"
	"fmt"

	"github.com/coreos/go-oidc/v3/oidc"
	"github.com/nexspence-oss/nexspence/internal/config"
	"golang.org/x/oauth2"
)

// ErrOIDCVerification is returned by OIDCService.ExchangeAndVerify for any
// validation failure (bad sig, wrong aud, expired, nonce mismatch). Callers
// should NOT distinguish sub-causes to clients — log server-side, return 401.
var ErrOIDCVerification = errors.New("oidc verification failed")

// OIDCClaims is the normalized user info extracted from a validated id_token.
// Field population is driven by OIDCConfig's *Claim settings.
type OIDCClaims struct {
	Subject   string
	Username  string
	Email     string
	Name      string
	FirstName string
	LastName  string
	Groups    []string
	Raw       map[string]any
}

// OIDCAuthenticator is the interface for OIDC operations (enables mocking).
type OIDCAuthenticator interface {
	AuthCodeURL(state, nonce, codeChallenge string) string
	ExchangeAndVerify(ctx context.Context, code, codeVerifier, expectedNonce string) (*OIDCClaims, error)
	TestConnection(ctx context.Context) error
	// EndSessionEndpoint returns the IdP's end_session_endpoint URL from OIDC
	// discovery metadata, or "" if the IdP does not publish it.
	EndSessionEndpoint() string
}

// OIDCService implements OIDCAuthenticator against a real IdP using go-oidc.
type OIDCService struct {
	cfg      config.OIDCConfig
	provider *oidc.Provider
	verifier *oidc.IDTokenVerifier
	oauth    *oauth2.Config
}

// NewOIDCService performs OIDC discovery against cfg.Issuer and prepares
// the oauth2.Config + id_token verifier. Returns an error if discovery fails
// — callers (main.go) should fail startup so misconfig is loud, not lazy.
func NewOIDCService(ctx context.Context, cfg config.OIDCConfig) (*OIDCService, error) {
	provider, err := oidc.NewProvider(ctx, cfg.Issuer)
	if err != nil {
		return nil, fmt.Errorf("oidc discovery: %w", err)
	}
	verifier := provider.Verifier(&oidc.Config{
		ClientID: cfg.ClientID,
		// Library defaults cover standard skew (5min). cfg.AllowedSkewSeconds is
		// reserved for future use if a custom Now-based tolerance becomes needed.
	})
	return &OIDCService{
		cfg:      cfg,
		provider: provider,
		verifier: verifier,
		oauth: &oauth2.Config{
			ClientID:     cfg.ClientID,
			ClientSecret: cfg.ClientSecret,
			RedirectURL:  cfg.RedirectURL,
			Endpoint:     provider.Endpoint(),
			Scopes:       cfg.Scopes,
		},
	}, nil
}

// AuthCodeURL returns the URL to redirect the browser to for the authorization
// code flow. state/nonce/codeChallenge are generated by the caller.
func (s *OIDCService) AuthCodeURL(state, nonce, codeChallenge string) string {
	return s.oauth.AuthCodeURL(state,
		oidc.Nonce(nonce),
		oauth2.SetAuthURLParam("code_challenge", codeChallenge),
		oauth2.SetAuthURLParam("code_challenge_method", "S256"),
	)
}

// ExchangeAndVerify exchanges the authorization code for tokens, validates
// the id_token (sig / iss / aud / exp / nonce), and returns normalized claims.
func (s *OIDCService) ExchangeAndVerify(ctx context.Context, code, codeVerifier, expectedNonce string) (*OIDCClaims, error) {
	tok, err := s.oauth.Exchange(ctx, code,
		oauth2.SetAuthURLParam("code_verifier", codeVerifier),
	)
	if err != nil {
		return nil, fmt.Errorf("%w: token exchange: %v", ErrOIDCVerification, err)
	}
	rawID, ok := tok.Extra("id_token").(string)
	if !ok || rawID == "" {
		return nil, fmt.Errorf("%w: missing id_token", ErrOIDCVerification)
	}
	idTok, err := s.verifier.Verify(ctx, rawID)
	if err != nil {
		return nil, fmt.Errorf("%w: id_token verify: %v", ErrOIDCVerification, err)
	}
	if idTok.Nonce != expectedNonce {
		return nil, fmt.Errorf("%w: nonce mismatch", ErrOIDCVerification)
	}

	var raw map[string]any
	if err := idTok.Claims(&raw); err != nil {
		return nil, fmt.Errorf("%w: claims decode: %v", ErrOIDCVerification, err)
	}
	return s.extractClaims(idTok.Subject, raw), nil
}

func (s *OIDCService) extractClaims(subject string, raw map[string]any) *OIDCClaims {
	getStr := func(key string) string {
		if v, ok := raw[key].(string); ok {
			return v
		}
		return ""
	}
	getStrSlice := func(key string) []string {
		v, ok := raw[key]
		if !ok {
			return nil
		}
		arr, ok := v.([]any)
		if !ok {
			return nil
		}
		out := make([]string, 0, len(arr))
		for _, x := range arr {
			if str, ok := x.(string); ok {
				out = append(out, str)
			}
		}
		return out
	}
	return &OIDCClaims{
		Subject:   subject,
		Username:  getStr(s.cfg.UsernameClaim),
		Email:     getStr(s.cfg.EmailClaim),
		Name:      getStr(s.cfg.NameClaim),
		FirstName: getStr("given_name"),
		LastName:  getStr("family_name"),
		Groups:    getStrSlice(s.cfg.GroupsClaim),
		Raw:       raw,
	}
}

// TestConnection re-runs discovery to confirm the IdP is reachable.
// Called at startup for a clear "oidc discovery ok/err" log line.
func (s *OIDCService) TestConnection(ctx context.Context) error {
	_, err := oidc.NewProvider(ctx, s.cfg.Issuer)
	return err
}

// endSessionMeta is used to extract end_session_endpoint from discovery JSON.
type endSessionMeta struct {
	EndSessionEndpoint string `json:"end_session_endpoint"`
}

// EndSessionEndpoint returns the IdP's end_session_endpoint, or "" if absent.
func (s *OIDCService) EndSessionEndpoint() string {
	var meta endSessionMeta
	if err := s.provider.Claims(&meta); err != nil {
		return ""
	}
	return meta.EndSessionEndpoint
}
